### ISSUE TITLE
inputIntProps using wrong input type

### ISSUE THREAD

**Issue by delaneyj** [garth/cerebral-module-ui-driver#2]
``` jsx
<Input
  type="number"
  {...bindings.inputIntProps('foo', {
    label: "Foo"
  })}
/>
```

Actually overrides the type back to `text`.  It probably makes sense for the inputInt to use `type="number"` by default anyways.

**Comment by garth** [comment]
You can override the props as follows

``` js
<Input
  {...Object.assign(bindings.inputIntProps('foo', {
    label: "Foo",
  }), { type: 'number' })}
/>
```

But you are probably right that type should be `number`.
