### ISSUE TITLE
Clarification in the docs.

### ISSUE THREAD

**Issue by delaneyj** [garth/cerebral-module-ui-driver#3]
For example in snabbdom

``` jsx
export default Component(formDriver.state(),({state,signals})=> {
  const bindings = formDriver.getBindings({state, signals});
  return (
    <Input
      {...bindings.inputProps('name', {
        label: 'Name',
        required: true
      })}
    />
  )
});
```

Why is the `formDriver.state()` needed?  Couldn't the binding be able to get that infomation from the call to create the bindings `const bindings = formDriver.getBindings({state, signals});`?

**Comment by garth** [comment]
ui-driver will work with both cerebral-react and cerebral-snabbdom. only cerebral-snabbdom can receive the whole state tree. But in either case it's better for the component to define the state that it needs from the tree.

formDriver.state() will instruct cerebral which state to get and what to call it when it's passed to render.

If you need to add other state, (which you probably do in most cases) then you can merge the objects with

``` js
Object.assign({
  something: ['something']
}, formDriver.state())
```

The other option might be to override `Component and have a`FormComponent` which would probably simplify the setup quite a bit. I may investigate that option. But  either way the current set of steps are all necessary.

Another alternative might be to do the filter when the state is passed to `getBindings` but this would only work in the snabbdom version, and I'd like to keep them as similar as possible.

**Comment by garth** [comment]
@delaneyj I hope that I've addressed this issue in the latest version?

**Comment by delaneyj** [comment]
Cool, I'll close for now.
