### ISSUE TITLE
Add babel-runtime

### ISSUE THREAD

**Issue by fmal** [garth/cerebral-module-ui-driver#5]
Hi Garth,

the compiled es5 code that is published on NPM has `Object.assign` calls and thus it breaks in IE11. Workaround for this is to include `Object.assign` polyfill in one's project, but even then it breaks because cerebral-addons dependency uses `Symbol()`. Is it an option to include `babel-runtime` as a dependency and pair it with `babel-plugin-runtime-transform`, so that compiled es5 code has references to polyfilling helpers? I think that should solve the issue. Another option is to publish es6 sources so It's possible to handle this in one's project setup.

Thanks

**Comment by garth** [comment]
I guess object.assign could be handled by changing to lodash. Not sure about the solution for symbol. The only problem with just exporting es6 is that most build setups are set to ignore node_modules.

I think that there should be a better es6=>es5 solution. I will look into it.

**Comment by fmal** [comment]
I've pushed a PR that adresses this, by excluding `.babelrc` file from the NPM package. Now i'm able to include `babel-runtime` in project-level `.babelrc`:

``` javascript
{
  "plugins": ["transform-runtime"]
}
```

and then include NPM package files in webpack config, e.g: 

``` javascript
module: {
    preLoaders: [
      {
        test: /\.js$/,
        include: [
          path.resolve(__dirname, 'src'),
          path.resolve(__dirname, 'node_modules/cerebral-module-ui-driver/lib')
        ],
        loader: 'babel-loader'
      }
    ]
}
```

This solves the aforementioned issues in legacy browsers.

**Comment by garth** [comment]
Thanks for for the PR!
