### ISSUE TITLE
Weird behavior in IE11

### ISSUE THREAD

**Issue by fmal** [garth/cerebral-module-ui-driver#7]
Hi Garth,

I wonder if you have come across this or maybe have some idea where the culprit might be hiding. In IE11 there is this weird behavior of "swallowing" single random characters while you type in an input field. The "swallowing" tekes place exactly when the `endValidate()` action runs and modifies the state tree. So to reproduce this you need to be typing at the same time when `endValidate()` triggers from the debounced chain in `valueChanged.js`. Unfortunately i'm not able to fix it anyhow and I even started wondering if it might be related to how Cerebral handles things internally.

I would really appreciate any help.

**Comment by garth** [comment]
Interesting. So if do run the same in other browsers it doesn't happen?

Would also be interesting to see if it's a timing/race condition. Perhaps you can try changing the debounce timeout to see if that has any effect on it?

**Comment by fmal** [comment]
Thanks for the quick reply. It seems to be IE11 specific issue, which unfortunately i need to support. In other browsers it runs perfectly fine. Changing the debounce timeout to ~600ms kinda fixes this behavior, because the endValidate runs after the user finishes typing. It looks like it's a race condition but only happening in IE. I'm not sure wheteher this is a browser bug/React/Cerebral thing, it's quite hard to debug 😠

**Comment by garth** [comment]
I guess this is probably "internal" code, but if you have some sample breaking code that you can share I would be happy to take a look?

**Comment by fmal** [comment]
Well, i have a simple login component, setup according to the package readme, nothing non standard. I wanted to setup some webpackbin demo or something, but it won't work in ie11 without babel-runtime polyfills etc. This is how it breaks: http://recordit.co/AIXhQB4yj2. I typed in "TEST_USER" to the input field and i was able to see U and E characters for a fraction of second, but apparently `onChange` event hasn't fired because at the same time `endValidate` triggered. I think this is really hard to track down and it's probably not a bug in cerebral-ui-driver, so I think i will go for the increased debounce timeout workaround for now and close the issue. Thanks for taking time to respond and suggestions 👍

**Comment by garth** [comment]
I'm not sure if it's going to help or not, but I'm currently looking into how to do ui-driver without modules to support cerebral 0.34. I will see if some of this logic can be simplified a little.
