### ISSUE TITLE
Cerebral 0.35 support 

### ISSUE THREAD

**Issue by fmal** [garth/cerebral-module-ui-driver#9]
Hi Garth,

i can see you've been busy adjusting some of your packages to support the latest Cerebral release, but seems like ui-driver is a little bit of "less regard". Just wanted to know if you have any plans on releasing an update? I'm using  it actively in my projects and currently it's a blocker for an upgrade to Cerebral 0.35. I have considered switching to some other component for handling forms, but i really like the way ui-driver works and would love to continue using it. 

Thanks

**Comment by garth** [comment]
I spent some time trying to update ui-driver for 0.34, but the changes to modules were quite significant and I ended up sicking with 0.33. Now that 0.35 is out and is quite a significant release, in terms for the future of cerebral, I will make another attempt. But I think that there will have to be some API changes.

So it will be updated to support 0.35, but it make take some time.

**Comment by fmal** [comment]
That's a great news, really looking forward to Cerebral 0.35 support. Ui-driver works perfectly fine with the 0.34 release, the only requirement being that `cerebral-provider-modules` is installed. Maybe it's just fine to say explicitly that ui-driver depends on the modules provider?

**Comment by garth** [comment]
@fmal Just released 0.10.0 with cerebral@0.35 support. Tests are green, but I don't currently have a real world app to double check it with so please let me know if you run into any issues.

**Comment by fmal** [comment]
Sorry for the late response (was on vacation). I've updated to the latest version today and it works nicely with cerebral 0.35! No issues as far as I can see and i'm using `ui-driver` quite a lot in my app. Thank you for taking time to adress this!
